/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Lucide-compatible icon exports backed by Hugeicons.
 * Generated by scripts/generate-hugeicons-compat.mjs — do not edit manually.
 */
"use client";

import { forwardRef, type ComponentPropsWithoutRef, type ForwardRefExoticComponent, type RefAttributes } from "react";
import { HugeiconsIcon } from "@hugeicons/react";
import {
  ActivityIcon as __Huge_ActivityIcon,
  AlarmClockMinusIcon as __Huge_AlarmClockMinusIcon,
  Alert02Icon as __Huge_Alert02Icon,
  AlertCircleIcon as __Huge_AlertCircleIcon,
  ArrowDown01Icon as __Huge_ArrowDown01Icon,
  ArrowDownIcon as __Huge_ArrowDownIcon,
  ArrowLeft01Icon as __Huge_ArrowLeft01Icon,
  ArrowRight01Icon as __Huge_ArrowRight01Icon,
  ArrowUp01Icon as __Huge_ArrowUp01Icon,
  ArrowUpDownIcon as __Huge_ArrowUpDownIcon,
  Attachment01Icon as __Huge_Attachment01Icon,
  Award01Icon as __Huge_Award01Icon,
  BalanceScaleIcon as __Huge_BalanceScaleIcon,
  BankIcon as __Huge_BankIcon,
  BarChartIcon as __Huge_BarChartIcon,
  BookOpen01Icon as __Huge_BookOpen01Icon,
  Building02Icon as __Huge_Building02Icon,
  CalculatorIcon as __Huge_CalculatorIcon,
  CalendarClockIcon as __Huge_CalendarClockIcon,
  CalendarDaysIcon as __Huge_CalendarDaysIcon,
  CalendarIcon as __Huge_CalendarIcon,
  CalendarRangeIcon as __Huge_CalendarRangeIcon,
  CancelCircleIcon as __Huge_CancelCircleIcon,
  CheckListIcon as __Huge_CheckListIcon,
  CheckmarkCircle02Icon as __Huge_CheckmarkCircle02Icon,
  ChevronLeftIcon as __Huge_ChevronLeftIcon,
  CircleCheckIcon as __Huge_CircleCheckIcon,
  ClipboardCheckIcon as __Huge_ClipboardCheckIcon,
  ClipboardPenIcon as __Huge_ClipboardPenIcon,
  Clock01Icon as __Huge_Clock01Icon,
  CloudUploadIcon as __Huge_CloudUploadIcon,
  CommandIcon as __Huge_CommandIcon,
  ComputerIcon as __Huge_ComputerIcon,
  Copy01Icon as __Huge_Copy01Icon,
  DashboardSquare01Icon as __Huge_DashboardSquare01Icon,
  Database01Icon as __Huge_Database01Icon,
  Delete02Icon as __Huge_Delete02Icon,
  DirectionLeft01Icon as __Huge_DirectionLeft01Icon,
  DollarSignIcon as __Huge_DollarSignIcon,
  DownloadIcon as __Huge_DownloadIcon,
  EditIcon as __Huge_EditIcon,
  ExternalLinkIcon as __Huge_ExternalLinkIcon,
  File01Icon as __Huge_File01Icon,
  FileImageIcon as __Huge_FileImageIcon,
  FileSearchIcon as __Huge_FileSearchIcon,
  FileSpreadsheetIcon as __Huge_FileSpreadsheetIcon,
  FlagIcon as __Huge_FlagIcon,
  FloppyDiskIcon as __Huge_FloppyDiskIcon,
  Folder01Icon as __Huge_Folder01Icon,
  FolderAddIcon as __Huge_FolderAddIcon,
  FolderOpenIcon as __Huge_FolderOpenIcon,
  FolderSearchIcon as __Huge_FolderSearchIcon,
  Forward01Icon as __Huge_Forward01Icon,
  GlobeIcon as __Huge_GlobeIcon,
  GraduationCapIcon as __Huge_GraduationCapIcon,
  GridIcon as __Huge_GridIcon,
  GripVerticalIcon as __Huge_GripVerticalIcon,
  Image02Icon as __Huge_Image02Icon,
  InboxIcon as __Huge_InboxIcon,
  InformationCircleIcon as __Huge_InformationCircleIcon,
  Invoice01Icon as __Huge_Invoice01Icon,
  Key01Icon as __Huge_Key01Icon,
  LayersIcon as __Huge_LayersIcon,
  LayoutGridIcon as __Huge_LayoutGridIcon,
  LibraryIcon as __Huge_LibraryIcon,
  Loading03Icon as __Huge_Loading03Icon,
  Logout01Icon as __Huge_Logout01Icon,
  Mail01Icon as __Huge_Mail01Icon,
  MailValidationIcon as __Huge_MailValidationIcon,
  MapPinIcon as __Huge_MapPinIcon,
  Medal01Icon as __Huge_Medal01Icon,
  Message01Icon as __Huge_Message01Icon,
  MinusPlusCircle01Icon as __Huge_MinusPlusCircle01Icon,
  MinusSignCircleIcon as __Huge_MinusSignCircleIcon,
  Money01Icon as __Huge_Money01Icon,
  Moon01Icon as __Huge_Moon01Icon,
  MoreHorizontalIcon as __Huge_MoreHorizontalIcon,
  MoreVerticalIcon as __Huge_MoreVerticalIcon,
  Mosque01Icon as __Huge_Mosque01Icon,
  MultiplicationSignIcon as __Huge_MultiplicationSignIcon,
  Notification01Icon as __Huge_Notification01Icon,
  PackageIcon as __Huge_PackageIcon,
  PanelLeftIcon as __Huge_PanelLeftIcon,
  PencilEdit01Icon as __Huge_PencilEdit01Icon,
  PieChart01Icon as __Huge_PieChart01Icon,
  PinIcon as __Huge_PinIcon,
  PlusSignCircleIcon as __Huge_PlusSignCircleIcon,
  PlusSignIcon as __Huge_PlusSignIcon,
  PowerIcon as __Huge_PowerIcon,
  PrinterIcon as __Huge_PrinterIcon,
  RadioIcon as __Huge_RadioIcon,
  RecordIcon as __Huge_RecordIcon,
  RefreshIcon as __Huge_RefreshIcon,
  Rotate01Icon as __Huge_Rotate01Icon,
  Search01Icon as __Huge_Search01Icon,
  SentIcon as __Huge_SentIcon,
  Settings02Icon as __Huge_Settings02Icon,
  Shield01Icon as __Huge_Shield01Icon,
  ShieldEnergyIcon as __Huge_ShieldEnergyIcon,
  ShieldUserIcon as __Huge_ShieldUserIcon,
  ShoppingBag01Icon as __Huge_ShoppingBag01Icon,
  SlidersHorizontalIcon as __Huge_SlidersHorizontalIcon,
  SmartPhone01Icon as __Huge_SmartPhone01Icon,
  SparklesIcon as __Huge_SparklesIcon,
  SquareLock01Icon as __Huge_SquareLock01Icon,
  SquareUnlock01Icon as __Huge_SquareUnlock01Icon,
  StackStarIcon as __Huge_StackStarIcon,
  Sun01Icon as __Huge_Sun01Icon,
  Tag01Icon as __Huge_Tag01Icon,
  Task01Icon as __Huge_Task01Icon,
  TelephoneIcon as __Huge_TelephoneIcon,
  TentIcon as __Huge_TentIcon,
  Tick02Icon as __Huge_Tick02Icon,
  TradeUpIcon as __Huge_TradeUpIcon,
  TruckIcon as __Huge_TruckIcon,
  Undo02Icon as __Huge_Undo02Icon,
  Upload01Icon as __Huge_Upload01Icon,
  UserAdd01Icon as __Huge_UserAdd01Icon,
  UserCheckIcon as __Huge_UserCheckIcon,
  UserGroupIcon as __Huge_UserGroupIcon,
  UserIcon as __Huge_UserIcon,
  UserMinusIcon as __Huge_UserMinusIcon,
  UserRemove01Icon as __Huge_UserRemove01Icon,
  ViewIcon as __Huge_ViewIcon,
  ViewOffIcon as __Huge_ViewOffIcon,
  Wifi01Icon as __Huge_Wifi01Icon,
  ZoomInAreaIcon as __Huge_ZoomInAreaIcon,
  ZoomOutAreaIcon as __Huge_ZoomOutAreaIcon,
} from "@hugeicons/core-free-icons";

export type LucideProps = ComponentPropsWithoutRef<"svg"> & {
  size?: number | string;
  absoluteStrokeWidth?: boolean;
};

export type LucideIcon = ForwardRefExoticComponent<
  LucideProps & RefAttributes<SVGSVGElement>
>;

const SIZE_CLASS_MAP: Record<string, number> = {
  "size-2": 8,
  "size-2.5": 10,
  "size-3": 12,
  "size-3.5": 14,
  "size-4": 16,
  "size-5": 20,
  "size-6": 24,
  "size-7": 28,
  "size-8": 32,
  "size-9": 36,
  "size-10": 40,
  "size-12": 48,
};

function resolveIconSize(size?: number | string, className?: string): number {
  if (typeof size === "number") return size;
  if (typeof size === "string") {
    const parsed = Number.parseFloat(size);
    if (Number.isFinite(parsed)) return parsed;
  }
  if (className) {
    for (const [token, px] of Object.entries(SIZE_CLASS_MAP)) {
      if (className.includes(token)) return px;
    }
  }
  return 16;
}

function createLucideIcon(
  iconData: Parameters<typeof HugeiconsIcon>[0]["icon"],
  displayName: string,
): LucideIcon {
  const Component = forwardRef<SVGSVGElement, LucideProps>(function LucideIcon(
    { className, size, color, strokeWidth, absoluteStrokeWidth: _absoluteStrokeWidth, ...props },
    ref,
  ) {
    return (
      <HugeiconsIcon
        ref={ref as never}
        icon={iconData}
        size={resolveIconSize(size, className)}
        color={(color as string | undefined) ?? "currentColor"}
        strokeWidth={typeof strokeWidth === "number" ? strokeWidth : 1.5}
        className={className}
        {...(props as any)}
      />
    );
  });
  Component.displayName = displayName;
  return Component;
}

const ICONS = {
  ActivityIcon: __Huge_ActivityIcon,
  AlarmClockMinusIcon: __Huge_AlarmClockMinusIcon,
  Alert02Icon: __Huge_Alert02Icon,
  AlertCircleIcon: __Huge_AlertCircleIcon,
  ArrowDown01Icon: __Huge_ArrowDown01Icon,
  ArrowDownIcon: __Huge_ArrowDownIcon,
  ArrowLeft01Icon: __Huge_ArrowLeft01Icon,
  ArrowRight01Icon: __Huge_ArrowRight01Icon,
  ArrowUp01Icon: __Huge_ArrowUp01Icon,
  ArrowUpDownIcon: __Huge_ArrowUpDownIcon,
  Attachment01Icon: __Huge_Attachment01Icon,
  Award01Icon: __Huge_Award01Icon,
  BalanceScaleIcon: __Huge_BalanceScaleIcon,
  BankIcon: __Huge_BankIcon,
  BarChartIcon: __Huge_BarChartIcon,
  BookOpen01Icon: __Huge_BookOpen01Icon,
  Building02Icon: __Huge_Building02Icon,
  CalculatorIcon: __Huge_CalculatorIcon,
  CalendarClockIcon: __Huge_CalendarClockIcon,
  CalendarDaysIcon: __Huge_CalendarDaysIcon,
  CalendarIcon: __Huge_CalendarIcon,
  CalendarRangeIcon: __Huge_CalendarRangeIcon,
  CancelCircleIcon: __Huge_CancelCircleIcon,
  CheckListIcon: __Huge_CheckListIcon,
  CheckmarkCircle02Icon: __Huge_CheckmarkCircle02Icon,
  ChevronLeftIcon: __Huge_ChevronLeftIcon,
  CircleCheckIcon: __Huge_CircleCheckIcon,
  ClipboardCheckIcon: __Huge_ClipboardCheckIcon,
  ClipboardPenIcon: __Huge_ClipboardPenIcon,
  Clock01Icon: __Huge_Clock01Icon,
  CloudUploadIcon: __Huge_CloudUploadIcon,
  CommandIcon: __Huge_CommandIcon,
  ComputerIcon: __Huge_ComputerIcon,
  Copy01Icon: __Huge_Copy01Icon,
  DashboardSquare01Icon: __Huge_DashboardSquare01Icon,
  Database01Icon: __Huge_Database01Icon,
  Delete02Icon: __Huge_Delete02Icon,
  DirectionLeft01Icon: __Huge_DirectionLeft01Icon,
  DollarSignIcon: __Huge_DollarSignIcon,
  DownloadIcon: __Huge_DownloadIcon,
  EditIcon: __Huge_EditIcon,
  ExternalLinkIcon: __Huge_ExternalLinkIcon,
  File01Icon: __Huge_File01Icon,
  FileImageIcon: __Huge_FileImageIcon,
  FileSearchIcon: __Huge_FileSearchIcon,
  FileSpreadsheetIcon: __Huge_FileSpreadsheetIcon,
  FlagIcon: __Huge_FlagIcon,
  FloppyDiskIcon: __Huge_FloppyDiskIcon,
  Folder01Icon: __Huge_Folder01Icon,
  FolderAddIcon: __Huge_FolderAddIcon,
  FolderOpenIcon: __Huge_FolderOpenIcon,
  FolderSearchIcon: __Huge_FolderSearchIcon,
  Forward01Icon: __Huge_Forward01Icon,
  GlobeIcon: __Huge_GlobeIcon,
  GraduationCapIcon: __Huge_GraduationCapIcon,
  GridIcon: __Huge_GridIcon,
  GripVerticalIcon: __Huge_GripVerticalIcon,
  Image02Icon: __Huge_Image02Icon,
  InboxIcon: __Huge_InboxIcon,
  InformationCircleIcon: __Huge_InformationCircleIcon,
  Invoice01Icon: __Huge_Invoice01Icon,
  Key01Icon: __Huge_Key01Icon,
  LayersIcon: __Huge_LayersIcon,
  LayoutGridIcon: __Huge_LayoutGridIcon,
  LibraryIcon: __Huge_LibraryIcon,
  Loading03Icon: __Huge_Loading03Icon,
  Logout01Icon: __Huge_Logout01Icon,
  Mail01Icon: __Huge_Mail01Icon,
  MailValidationIcon: __Huge_MailValidationIcon,
  MapPinIcon: __Huge_MapPinIcon,
  Medal01Icon: __Huge_Medal01Icon,
  Message01Icon: __Huge_Message01Icon,
  MinusPlusCircle01Icon: __Huge_MinusPlusCircle01Icon,
  MinusSignCircleIcon: __Huge_MinusSignCircleIcon,
  Money01Icon: __Huge_Money01Icon,
  Moon01Icon: __Huge_Moon01Icon,
  MoreHorizontalIcon: __Huge_MoreHorizontalIcon,
  MoreVerticalIcon: __Huge_MoreVerticalIcon,
  Mosque01Icon: __Huge_Mosque01Icon,
  MultiplicationSignIcon: __Huge_MultiplicationSignIcon,
  Notification01Icon: __Huge_Notification01Icon,
  PackageIcon: __Huge_PackageIcon,
  PanelLeftIcon: __Huge_PanelLeftIcon,
  PencilEdit01Icon: __Huge_PencilEdit01Icon,
  PieChart01Icon: __Huge_PieChart01Icon,
  PinIcon: __Huge_PinIcon,
  PlusSignCircleIcon: __Huge_PlusSignCircleIcon,
  PlusSignIcon: __Huge_PlusSignIcon,
  PowerIcon: __Huge_PowerIcon,
  PrinterIcon: __Huge_PrinterIcon,
  RadioIcon: __Huge_RadioIcon,
  RecordIcon: __Huge_RecordIcon,
  RefreshIcon: __Huge_RefreshIcon,
  Rotate01Icon: __Huge_Rotate01Icon,
  Search01Icon: __Huge_Search01Icon,
  SentIcon: __Huge_SentIcon,
  Settings02Icon: __Huge_Settings02Icon,
  Shield01Icon: __Huge_Shield01Icon,
  ShieldEnergyIcon: __Huge_ShieldEnergyIcon,
  ShieldUserIcon: __Huge_ShieldUserIcon,
  ShoppingBag01Icon: __Huge_ShoppingBag01Icon,
  SlidersHorizontalIcon: __Huge_SlidersHorizontalIcon,
  SmartPhone01Icon: __Huge_SmartPhone01Icon,
  SparklesIcon: __Huge_SparklesIcon,
  SquareLock01Icon: __Huge_SquareLock01Icon,
  SquareUnlock01Icon: __Huge_SquareUnlock01Icon,
  StackStarIcon: __Huge_StackStarIcon,
  Sun01Icon: __Huge_Sun01Icon,
  Tag01Icon: __Huge_Tag01Icon,
  Task01Icon: __Huge_Task01Icon,
  TelephoneIcon: __Huge_TelephoneIcon,
  TentIcon: __Huge_TentIcon,
  Tick02Icon: __Huge_Tick02Icon,
  TradeUpIcon: __Huge_TradeUpIcon,
  TruckIcon: __Huge_TruckIcon,
  Undo02Icon: __Huge_Undo02Icon,
  Upload01Icon: __Huge_Upload01Icon,
  UserAdd01Icon: __Huge_UserAdd01Icon,
  UserCheckIcon: __Huge_UserCheckIcon,
  UserGroupIcon: __Huge_UserGroupIcon,
  UserIcon: __Huge_UserIcon,
  UserMinusIcon: __Huge_UserMinusIcon,
  UserRemove01Icon: __Huge_UserRemove01Icon,
  ViewIcon: __Huge_ViewIcon,
  ViewOffIcon: __Huge_ViewOffIcon,
  Wifi01Icon: __Huge_Wifi01Icon,
  ZoomInAreaIcon: __Huge_ZoomInAreaIcon,
  ZoomOutAreaIcon: __Huge_ZoomOutAreaIcon,
} as const;

export const Activity = createLucideIcon(ICONS.ActivityIcon, "Activity");
export const AlertCircle = createLucideIcon(ICONS.AlertCircleIcon, "AlertCircle");
export const AlertTriangle = createLucideIcon(ICONS.Alert02Icon, "AlertTriangle");
export const ArrowDown = createLucideIcon(ICONS.ArrowDownIcon, "ArrowDown");
export const ArrowDownIcon = createLucideIcon(ICONS.ArrowDown01Icon, "ArrowDownIcon");
export const ArrowLeft = createLucideIcon(ICONS.ArrowLeft01Icon, "ArrowLeft");
export const ArrowRight = createLucideIcon(ICONS.ArrowRight01Icon, "ArrowRight");
export const ArrowUp = createLucideIcon(ICONS.ArrowUp01Icon, "ArrowUp");
export const ArrowUpDown = createLucideIcon(ICONS.ArrowUpDownIcon, "ArrowUpDown");
export const Award = createLucideIcon(ICONS.Award01Icon, "Award");
export const Banknote = createLucideIcon(ICONS.Money01Icon, "Banknote");
export const BarChart3 = createLucideIcon(ICONS.BarChartIcon, "BarChart3");
export const Bell = createLucideIcon(ICONS.Notification01Icon, "Bell");
export const BookOpen = createLucideIcon(ICONS.BookOpen01Icon, "BookOpen");
export const Building2 = createLucideIcon(ICONS.Building02Icon, "Building2");
export const Calculator = createLucideIcon(ICONS.CalculatorIcon, "Calculator");
export const Calendar = createLucideIcon(ICONS.CalendarIcon, "Calendar");
export const CalendarClock = createLucideIcon(ICONS.CalendarClockIcon, "CalendarClock");
export const CalendarDays = createLucideIcon(ICONS.CalendarDaysIcon, "CalendarDays");
export const CalendarRange = createLucideIcon(ICONS.CalendarRangeIcon, "CalendarRange");
export const Check = createLucideIcon(ICONS.Tick02Icon, "Check");
export const CheckCircle = createLucideIcon(ICONS.CheckmarkCircle02Icon, "CheckCircle");
export const CheckCircle2 = createLucideIcon(ICONS.CheckmarkCircle02Icon, "CheckCircle2");
export const CheckIcon = createLucideIcon(ICONS.Tick02Icon, "CheckIcon");
export const ChevronDown = createLucideIcon(ICONS.ArrowDown01Icon, "ChevronDown");
export const ChevronDownIcon = createLucideIcon(ICONS.ArrowDown01Icon, "ChevronDownIcon");
export const ChevronLeft = createLucideIcon(ICONS.ArrowLeft01Icon, "ChevronLeft");
export const ChevronLeftIcon = createLucideIcon(ICONS.ChevronLeftIcon, "ChevronLeftIcon");
export const ChevronRight = createLucideIcon(ICONS.ArrowRight01Icon, "ChevronRight");
export const ChevronRightIcon = createLucideIcon(ICONS.ArrowRight01Icon, "ChevronRightIcon");
export const ChevronUpIcon = createLucideIcon(ICONS.ArrowUp01Icon, "ChevronUpIcon");
export const ChevronsUpDown = createLucideIcon(ICONS.ArrowUpDownIcon, "ChevronsUpDown");
export const Church = createLucideIcon(ICONS.Mosque01Icon, "Church");
export const Circle = createLucideIcon(ICONS.RecordIcon, "Circle");
export const CircleCheckIcon = createLucideIcon(ICONS.CircleCheckIcon, "CircleCheckIcon");
export const ClipboardCheck = createLucideIcon(ICONS.ClipboardCheckIcon, "ClipboardCheck");
export const ClipboardEdit = createLucideIcon(ICONS.ClipboardPenIcon, "ClipboardEdit");
export const ClipboardList = createLucideIcon(ICONS.Task01Icon, "ClipboardList");
export const Clock = createLucideIcon(ICONS.Clock01Icon, "Clock");
export const Command = createLucideIcon(ICONS.CommandIcon, "Command");
export const Copy = createLucideIcon(ICONS.Copy01Icon, "Copy");
export const DollarSign = createLucideIcon(ICONS.DollarSignIcon, "DollarSign");
export const Download = createLucideIcon(ICONS.DownloadIcon, "Download");
export const Edit = createLucideIcon(ICONS.EditIcon, "Edit");
export const Ellipsis = createLucideIcon(ICONS.MoreHorizontalIcon, "Ellipsis");
export const ExternalLink = createLucideIcon(ICONS.ExternalLinkIcon, "ExternalLink");
export const Eye = createLucideIcon(ICONS.ViewIcon, "Eye");
export const EyeOff = createLucideIcon(ICONS.ViewOffIcon, "EyeOff");
export const FileImage = createLucideIcon(ICONS.FileImageIcon, "FileImage");
export const FileSearch = createLucideIcon(ICONS.FileSearchIcon, "FileSearch");
export const FileSpreadsheet = createLucideIcon(ICONS.FileSpreadsheetIcon, "FileSpreadsheet");
export const FileStack = createLucideIcon(ICONS.StackStarIcon, "FileStack");
export const FileText = createLucideIcon(ICONS.File01Icon, "FileText");
export const Flag = createLucideIcon(ICONS.FlagIcon, "Flag");
export const Folder = createLucideIcon(ICONS.Folder01Icon, "Folder");
export const FolderOpen = createLucideIcon(ICONS.FolderOpenIcon, "FolderOpen");
export const FolderPlus = createLucideIcon(ICONS.FolderAddIcon, "FolderPlus");
export const FolderSearch = createLucideIcon(ICONS.FolderSearchIcon, "FolderSearch");
export const Forward = createLucideIcon(ICONS.Forward01Icon, "Forward");
export const Globe = createLucideIcon(ICONS.GlobeIcon, "Globe");
export const GraduationCap = createLucideIcon(ICONS.GraduationCapIcon, "GraduationCap");
export const Grid3X3 = createLucideIcon(ICONS.GridIcon, "Grid3X3");
export const GripVertical = createLucideIcon(ICONS.GripVerticalIcon, "GripVertical");
export const History = createLucideIcon(ICONS.Clock01Icon, "History");
export const Image = createLucideIcon(ICONS.Image02Icon, "Image");
export const ImageIcon = createLucideIcon(ICONS.Image02Icon, "ImageIcon");
export const Inbox = createLucideIcon(ICONS.InboxIcon, "Inbox");
export const Info = createLucideIcon(ICONS.InformationCircleIcon, "Info");
export const InfoIcon = createLucideIcon(ICONS.InformationCircleIcon, "InfoIcon");
export const Key = createLucideIcon(ICONS.Key01Icon, "Key");
export const KeyRound = createLucideIcon(ICONS.Key01Icon, "KeyRound");
export const Landmark = createLucideIcon(ICONS.BankIcon, "Landmark");
export const Layers = createLucideIcon(ICONS.LayersIcon, "Layers");
export const LayoutDashboard = createLucideIcon(ICONS.DashboardSquare01Icon, "LayoutDashboard");
export const LayoutGrid = createLucideIcon(ICONS.LayoutGridIcon, "LayoutGrid");
export const Library = createLucideIcon(ICONS.LibraryIcon, "Library");
export const ListChecks = createLucideIcon(ICONS.CheckListIcon, "ListChecks");
export const Loader2 = createLucideIcon(ICONS.Loading03Icon, "Loader2");
export const Loader2Icon = createLucideIcon(ICONS.Loading03Icon, "Loader2Icon");
export const Lock = createLucideIcon(ICONS.SquareLock01Icon, "Lock");
export const LockOpen = createLucideIcon(ICONS.SquareUnlock01Icon, "LockOpen");
export const LogOut = createLucideIcon(ICONS.Logout01Icon, "LogOut");
export const Mail = createLucideIcon(ICONS.Mail01Icon, "Mail");
export const MailCheck = createLucideIcon(ICONS.MailValidationIcon, "MailCheck");
export const MailIcon = createLucideIcon(ICONS.Mail01Icon, "MailIcon");
export const MapPin = createLucideIcon(ICONS.MapPinIcon, "MapPin");
export const Medal = createLucideIcon(ICONS.Medal01Icon, "Medal");
export const MessageSquare = createLucideIcon(ICONS.Message01Icon, "MessageSquare");
export const MessageSquareText = createLucideIcon(ICONS.Message01Icon, "MessageSquareText");
export const Minus = createLucideIcon(ICONS.AlarmClockMinusIcon, "Minus");
export const MinusCircle = createLucideIcon(ICONS.MinusSignCircleIcon, "MinusCircle");
export const MinusIcon = createLucideIcon(ICONS.AlarmClockMinusIcon, "MinusIcon");
export const Monitor = createLucideIcon(ICONS.ComputerIcon, "Monitor");
export const Moon = createLucideIcon(ICONS.Moon01Icon, "Moon");
export const MoreHorizontal = createLucideIcon(ICONS.MoreHorizontalIcon, "MoreHorizontal");
export const MoreHorizontalIcon = createLucideIcon(ICONS.MoreHorizontalIcon, "MoreHorizontalIcon");
export const MoreVertical = createLucideIcon(ICONS.MoreVerticalIcon, "MoreVertical");
export const OctagonXIcon = createLucideIcon(ICONS.CancelCircleIcon, "OctagonXIcon");
export const Package = createLucideIcon(ICONS.PackageIcon, "Package");
export const PanelLeftIcon = createLucideIcon(ICONS.PanelLeftIcon, "PanelLeftIcon");
export const Paperclip = createLucideIcon(ICONS.Attachment01Icon, "Paperclip");
export const Pencil = createLucideIcon(ICONS.PencilEdit01Icon, "Pencil");
export const Phone = createLucideIcon(ICONS.TelephoneIcon, "Phone");
export const PieChart = createLucideIcon(ICONS.PieChart01Icon, "PieChart");
export const Pin = createLucideIcon(ICONS.PinIcon, "Pin");
export const Plus = createLucideIcon(ICONS.PlusSignIcon, "Plus");
export const PlusCircle = createLucideIcon(ICONS.MinusPlusCircle01Icon, "PlusCircle");
export const PlusCircleIcon = createLucideIcon(ICONS.PlusSignCircleIcon, "PlusCircleIcon");
export const Power = createLucideIcon(ICONS.PowerIcon, "Power");
export const Printer = createLucideIcon(ICONS.PrinterIcon, "Printer");
export const Radio = createLucideIcon(ICONS.RadioIcon, "Radio");
export const Receipt = createLucideIcon(ICONS.Invoice01Icon, "Receipt");
export const RefreshCcw = createLucideIcon(ICONS.RefreshIcon, "RefreshCcw");
export const RefreshCw = createLucideIcon(ICONS.RefreshIcon, "RefreshCw");
export const RotateCcw = createLucideIcon(ICONS.Rotate01Icon, "RotateCcw");
export const Save = createLucideIcon(ICONS.FloppyDiskIcon, "Save");
export const Scale = createLucideIcon(ICONS.BalanceScaleIcon, "Scale");
export const Search = createLucideIcon(ICONS.Search01Icon, "Search");
export const SearchIcon = createLucideIcon(ICONS.Search01Icon, "SearchIcon");
export const Send = createLucideIcon(ICONS.SentIcon, "Send");
export const ServerOff = createLucideIcon(ICONS.Database01Icon, "ServerOff");
export const Settings2 = createLucideIcon(ICONS.Settings02Icon, "Settings2");
export const Shield = createLucideIcon(ICONS.Shield01Icon, "Shield");
export const ShieldAlert = createLucideIcon(ICONS.ShieldEnergyIcon, "ShieldAlert");
export const ShieldCheck = createLucideIcon(ICONS.ShieldEnergyIcon, "ShieldCheck");
export const ShieldOff = createLucideIcon(ICONS.ShieldUserIcon, "ShieldOff");
export const ShoppingBag = createLucideIcon(ICONS.ShoppingBag01Icon, "ShoppingBag");
export const Signpost = createLucideIcon(ICONS.DirectionLeft01Icon, "Signpost");
export const SlidersHorizontal = createLucideIcon(ICONS.SlidersHorizontalIcon, "SlidersHorizontal");
export const Smartphone = createLucideIcon(ICONS.SmartPhone01Icon, "Smartphone");
export const Sparkles = createLucideIcon(ICONS.SparklesIcon, "Sparkles");
export const Sun = createLucideIcon(ICONS.Sun01Icon, "Sun");
export const Tag = createLucideIcon(ICONS.Tag01Icon, "Tag");
export const Tags = createLucideIcon(ICONS.Tag01Icon, "Tags");
export const Tent = createLucideIcon(ICONS.TentIcon, "Tent");
export const Trash2 = createLucideIcon(ICONS.Delete02Icon, "Trash2");
export const TrendingUp = createLucideIcon(ICONS.TradeUpIcon, "TrendingUp");
export const TriangleAlertIcon = createLucideIcon(ICONS.Alert02Icon, "TriangleAlertIcon");
export const Trophy = createLucideIcon(ICONS.Award01Icon, "Trophy");
export const Truck = createLucideIcon(ICONS.TruckIcon, "Truck");
export const Undo2 = createLucideIcon(ICONS.Undo02Icon, "Undo2");
export const Upload = createLucideIcon(ICONS.Upload01Icon, "Upload");
export const UploadCloud = createLucideIcon(ICONS.CloudUploadIcon, "UploadCloud");
export const User = createLucideIcon(ICONS.UserIcon, "User");
export const UserCheck = createLucideIcon(ICONS.UserCheckIcon, "UserCheck");
export const UserMinus = createLucideIcon(ICONS.UserMinusIcon, "UserMinus");
export const UserPlus = createLucideIcon(ICONS.UserAdd01Icon, "UserPlus");
export const UserRound = createLucideIcon(ICONS.UserIcon, "UserRound");
export const UserX = createLucideIcon(ICONS.UserRemove01Icon, "UserX");
export const Users = createLucideIcon(ICONS.UserGroupIcon, "Users");
export const Wifi = createLucideIcon(ICONS.Wifi01Icon, "Wifi");
export const X = createLucideIcon(ICONS.MultiplicationSignIcon, "X");
export const XCircle = createLucideIcon(ICONS.CancelCircleIcon, "XCircle");
export const XIcon = createLucideIcon(ICONS.MultiplicationSignIcon, "XIcon");
export const ZoomIn = createLucideIcon(ICONS.ZoomInAreaIcon, "ZoomIn");
export const ZoomOut = createLucideIcon(ICONS.ZoomOutAreaIcon, "ZoomOut");
